server:
  port: 8081
  servlet:
    context-path: /1099services
spring:
  profiles:
    active: ${SERVER_INSTANCE_MODE:development}
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  datasource: # Set here configurations for the database connection
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
    tomcat:
      initial-size: 30
      max-active: 100
      max-idle: 20

  jpa: # JPA / HIBERNATE
    show-sql: true # Show or not log for each sql query
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # Naming strategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Allows Hibernate to generate SQL optimized for a particular DBMS
springdoc:
  show-actuator: true
  swagger-ui:
    operations-sorter: method